# Usar una imagen base de Node.js para instalar las dependencias
FROM node:16 AS build

# Definir el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de tu aplicación Angular al contenedor
COPY package*.json ./

# Instalar las dependencias de Angular
RUN npm install

# Copiar el resto de los archivos del proyecto al contenedor
COPY . .

# Construir la aplicación Angular para producción
RUN npm run build --prod

# Usar una imagen base ligera de Nginx para servir la aplicación
FROM nginx:alpine

# Copiar los archivos de construcción desde la etapa anterior
COPY --from=build /app/dist/ /usr/share/nginx/html

# Exponer el puerto en el que Nginx estará escuchando
EXPOSE 80

# Iniciar Nginx cuando el contenedor se ejecute
CMD ["nginx", "-g", "daemon off;"]