name: SonarQube

on:
  push:
    branches:
      - main
      - develop

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest  # Utiliza Ubuntu más reciente para las máquinas virtuales

    steps:
      # Paso 1: Checkout del código
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Asegúrate de obtener todo el historial de commits

      # Paso 2: Instalar dependencias de sistema necesarias para ejecutar Chrome en headless
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2 \
            libx11-xcb1 \
            libglib2.0-0 \
            libnss3 \
            libgdk-pixbuf2.0-0 \
            libxss1 \
            fonts-liberation \
            libappindicator3-1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libgbm1 \
            libxrandr2 \
            libxcomposite1 \
            libxdamage1 \
            libgtk-3-0 \
            xvfb  # Asegúrate de que Xvfb esté disponible
          npm install  # Instalar dependencias de Node.js necesarias

      # Paso 3: Instalar Angular CLI de forma global
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Paso 4: Configurar Xvfb y ejecutar las pruebas de Angular en headless
      - name: Set up Xvfb and run tests
        run: |
          export DISPLAY=:99  # Necesario para que Chrome headless funcione en CI
          Xvfb :99 -screen 0 1280x1024x24 &  # Iniciar Xvfb en un segundo plano
          ng test --watch=false --code-coverage  # Ejecutar las pruebas en modo headless

      # Paso 5: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Usar el token de autenticación de SonarQube
        with:
          args: >
            -Dsonar.projectKey=Front_Web
            -Dsonar.organization=mi-org
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.exclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.host.url=https://sonarcloud.io  # URL de SonarCloud