name: SonarQube
on:
  push:
    branches:
      - main
      - develop

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 \
            libglib2.0-0 \
            libnss3 \
            libgdk-pixbuf2.0-0 \
            libxss1 \
            libasound2 \
            fonts-liberation \
            libappindicator3-1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libgbm1 \
            libxrandr2 \
            libxcomposite1 \
            libxdamage1 \
            libgdk-pixbuf2.0-0 \
            libgtk-3-0 \
            google-chrome-stable \
            xvfb  # Asegúrate de instalar Xvfb

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run tests with coverage (headless)
        run: ng test --watch=false --code-coverage 

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Front_Web
            -Dsonar.organization=mi-org
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.exclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.host.url=https://sonarcloud.io